from enum import Enum
import os

EXECUTION_PATH = os.getcwd()

RASPBERRY_PI_MODE = Enum('RASPBERRY_PI_MODE', 'ENTRANCE EXIT')

OPERATION_MODE = RASPBERRY_PI_MODE.ENTRANCE

MODEL_PATH = os.path.join(EXECUTION_PATH, 'models')

OUTPUT_FILE_PATH = os.path.join(EXECUTION_PATH, 'output')

FRAMES_PER_SECOND = 30

LOG_PROGRESS = True

RETURN_DETECTED_FRAME = True

MINIMUM_PERCENTAGE_PROBABILITY = 30

DISPLAY_PERCENTAGE_PROBABILITY = False

DISDPLAY_OBJECT_NAME = True

SAVE_DETECTED_VIDEO = True

if __name__ == '__main__':
    print(dir())
